id: P004485
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:25:58.807781
source_metadata:
  id: bdr:W8LS18505
  title: བོད་ཀྱི་དེང་རབས་རྩོམ་ཡིག་གཅེས་བཏུས།
  author: ''
  volumes:
    4ae314571ef948b3ae3f7d53d6a82c10:
      image_group_id: I8LS18507
      title: ''
      volume_number: 1
      total_pages: 319
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
